#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Casey DeLorme <cdelorme@gmail.com>

# path and flags
NAME=xboxdrv
CONFIG=/etc/default/$NAME
DAEMON=/usr/bin/$NAME
DAEMON_ARGS="-D -c $CONFIG --detach"

# exit if not installed
[ -x "$DAEMON" ] || exit 0

# define methods, no error handling, just raw execution
do_start()
{
    # rmmod xpad if loaded
    [ $(lsmod | grep -c xpad) -gt 0 ] && rmmod xpad

    # attempt to run
    $DAEMON $DAEMON_ARGS
}

do_stop()
{
    # look for and attempt to stop
    [ $(ps aux | grep -v grep | grep -c "$DAEMON $DAEMON_ARGS") -eq 1 ] && kill -9 $(ps aux | grep -v grep | grep "$DAEMON $DAEMON_ARGS" | awk '{print $2}')

    # attempt to reload xpad
    [ $(ps aux | grep -v grep | grep -c "$DAEMON $DAEMON_ARGS") -eq 0 ] && modprobe xpad
}

case "$1" in
  start)
    echo "starting $NAME"
	do_start
	;;
  stop)
    echo "stopping $NAME"
	do_stop
	;;
  status)
      [ $(ps aux | grep -v grep | grep -c "$DAEMON $DAEMON_ARGS") -eq 1 ] && echo "$NAME [started]" || echo "$NAME [stopped]"
	;;
  restart)
    echo "restarting $NAME"
	do_stop
    do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac

:
