#!/bin/bash

# requires root privileges
[ $(id -u) -ne 0 ] && echo "must be executed with root permissions..." && exit 1

# template
[ -z "$username" ] && username="banana"
[ -z "$password" ] && password="hammock"
[ -z "$dot_files" ] && dot_files="https://raw.githubusercontent.com/cdelorme/dot-files/master/install"
[ -z "$github_username" ] && github_username=$username
[ -z "$create_ssh" ] && create_ssh="y"
[ -z "$ssh_port" ] && ssh_port=22
[ -z "$system_hostname" ] && system_hostname="dev"
[ -z "$timezone" ] && timezone="US/Eastern"
[ -z "$jis" ] && jis="y"
[ -z "$cronfile" ] && cronfile="/var/spool/cron/crontabs/${username}"
[ -z "$remote_source" ] && remote_source="https://raw.githubusercontent.com/cdelorme/system-setup/develop/"

# web
[ -z "$install_processing_tools" ] && install_processing_tools="y"
[ -z "$install_mongodb" ] && install_mongodb="y"
[ -z "$public_mongodb" ] && public_mongodb="n"
[ -z "$install_mariadb" ] && install_mariadb="y"
[ -z "$public_mariadb" ] && public_mariadb="n"
[ -z "$install_phpfpm" ] && install_phpfpm="y"
[ -z "$public_phpfpm" ] && public_phpfpm="n"
[ -z "$install_msmtp" ] && install_msmtp="n"
[ -z "$msmtp_username" ] && msmtp_username="$username"
[ -z "$msmtp_password" ] && msmtp_password="$password"

# dev
[ -z "$install_mdadm" ] && install_mdadm="y"
[ -z "$install_samba" ] && install_samba="y"
[ -z "$install_weechat" ] && install_weechat="y"
[ -z "$install_wireless" ] && install_wireless="y"
[ -z "$install_transmission" ] && install_transmission="y"
[ -z "$install_openbox" ] && install_openbox="y"
[ -z "$install_compton" ] && install_compton="y"
[ -z "$install_web" ] && install_web="y"

# remote commands (would use curl, but base debian does not come with curl)
dl_cmd="wget --no-check-certificate -O"
source_cmd="wget --no-check-certificate -qO-"

# begin execution
[ -f "scripts/dev.sh" ] && . "scripts/dev.sh" || eval "$($source_cmd ${remote_source}scripts/dev.sh)"