#!/bin/bash

# requires root privileges
[ $(id -u) -ne 0 ] && echo "must be executed with root permissions..." && exit 1

# allow username and password from current environment
[ -z "$username" ] && username="banana"
[ -z "$password" ] && password="hammock"

# set required variables
[ -z "$dot_files" ] && dot_files="https://raw.githubusercontent.com/cdelorme/dot-files/master/install"
[ -z "$github_username" ] && github_username=$username
[ -z "$create_ssh" ] && create_ssh="y"
[ -z "$ssh_port" ] && ssh_port=22
[ -z "$system_hostname" ] && system_hostname="template"
[ -z "$timezone" ] && timezone="US/Eastern"
[ -z "$jis" ] && jis="y"
[ -z "$cronfile" ] && cronfile="/var/spool/cron/crontabs/${username}"
[ -z "$remote_source" ] && remote_source="https://raw.githubusercontent.com/cdelorme/system-setup/develop/"

# remote commands (would use curl, but base debian does not come with curl)
dl_cmd="wget --no-check-certificate -O"
source_cmd="wget --no-check-certificate -qO-"

# begin execution
[ -f "scripts/template.sh" ] && . "scripts/template.sh" || eval "$($source_cmd ${remote_source}scripts/template.sh)"