#!/bin/bash

# requires root privileges
[ $(id -u) -ne 0 ] && echo "must be executed with root permissions..." && exit 1

# allow username and password from current environment
[ -z "$username" ] && username="banana"
[ -z "$password" ] && password="hammock"

# set required variables
dot_files="https://raw.githubusercontent.com/cdelorme/dot-files/master/install"
github_username=$username
create_ssh="y"
ssh_port=22
system_hostname="template"
timezone="US/Eastern"
jis="y"
cronfile="/var/spool/cron/crontabs/${username}"
remote_source="https://raw.githubusercontent.com/cdelorme/system-setup/develop/"

# remote commands
if which curl &> /dev/null
then
    dl_cmd="curl -Lo"
    source_cmd="curl -s"
elif which wget &> /dev/null
then
    dl_cmd="wget --no-check-certificate -O"
    source_cmd="wget --no-check-certificate -qO-"
fi

# begin execution
[ -f "scripts/template.sh" ] && . "scripts/template.sh" || eval "$($source_cmd ${remote_source}scripts/template.sh)"