#!/bin/sh
which xset &>/dev/null && (xset r rate 250 25 & xset b off & xset m 7 5)
which xrdb &>/dev/null && [ -f "$HOME/.Xresources" ] || [ -L "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"
which xdg-user-dirs-update &>/dev/null && (xdg-user-dirs-update)
which nosleep-daemon &>/dev/null && (nosleep-daemon) &
which compton &>/dev/null && (compton) &
which hsetroot &>/dev/null && (sleep 1 && hsetroot -solid "#001E27") &
which tint2 &>/dev/null && (sleep 3 && tint2) &
which fehbg &>/dev/null && (sleep 4 && fehbg) &
which pasystray &>/dev/null && (sleep 5 && pasystray) &
which clipit &>/dev/null && (sleep 5 && clipit) &
which ibus-daemon &>/dev/null && (sleep 5 && ibus-daemon -d) &
which connman-ui-gtk &>/dev/null && (sleep 5 && connman-ui-gtk) &
if [ $(xrandr -d :0 -q | grep -c " connected") -ge 2 ]
then
	which conky &> /dev/null && (sleep 10 && conky -d -q -c ~/.conky/rc1) &
	which conky &> /dev/null && (sleep 10 && conky -d -q -c ~/.conky/rc2) &
else
	which conky &> /dev/null && (sleep 10 && conky -d -q) &
fi
