#!/bin/bash
set -eufxo pipefail
IFS=$'\n\t'

# @todo(casey): execute btrfs snapshot prior to running updates

# set headless flags for debian package updates
unset UCF_FORCE_CONFNEW
export UCF_FORCE_CONFOLD=true
export DEBIAN_FRONTEND=noninteractive

# update mirror (fallback to old mirror on failure)
mv -f /etc/apt/sources.list /etc/apt/sources.list.bak
netselect-apt -c US -fsno /etc/apt/sources.list stable
aptitude clean
if ! aptitude update
then
    mv -f /etc/apt/sources.list.bak /etc/apt/sources.list
    aptitude clean
    aptitude update
fi
aptitude upgrade -yq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
update-command-not-found
