#!/bin/bash
set -eufxo pipefail
IFS=$'\n\t'

# @todo(casey): execute btrfs snapshot prior to running updates

# set headless flags for debian package updates
unset UCF_FORCE_CONFNEW
export UCF_FORCE_CONFOLD=true
export DEBIAN_FRONTEND=noninteractive

# update mirror (fallback to old mirror on failure)
aptitude clean
aptitude update
aptitude upgrade -yq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

# update youtube-dl
which youtube-dl &>/dev/null && youtube-dl -U

# update command list
update-command-not-found
