#!/bin/bash

# @todo(casey): execute btrfs snapshot prior to running updates

# set headless flags for debian package updates
unset UCF_FORCE_CONFOLD
export UCF_FORCE_CONFNEW=true
export DEBIAN_FRONTEND=noninteractive

# update best mirror (fallback to old config on failure)
mv /etc/apt/sources.list /etc/apt/sources.list.bak
netselect-apt -sn -o /etc/apt/sources.list $(lsb_release -c | cut -f2)
aptitude clean
if ! aptitude update
then
    mv /etc/apt/sources.list.bak /etc/apt/sources.list
    aptitude clean
    aptitude update
fi
aptitude upgrade -yq -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-confold"
update-command-not-found