#!/bin/sh
# Configuration File
# Set the variables below to your liking and initiate the script to process

# Username for customization (default: user)
USERNAME=user
# Username may already exist, it will be created otherwise

# Password if user does not yet exist (OPTIONAL, default: pass1)
PASSWORD=pass1
# If above user has to be created, this will set their password.

# Development Directory (default: /home/src)
DEV_DIR=/home/src
# Choose a location with at least 6GB of space so we can compile a kernel and xen there

# Keep compiled source files after built & installed (default: false)
KEEP_DEV=false

# Add trim support to `/etc/lvm/lvm.conf` and cron-job fstrim weekly (default: true)
TRIM=true

# Custom SSH Port (default: 22)
SSH_PORT=22

# Headless eg No Gui (default: false)
HEADLESS=false

# Dual Interfaces for Internet Output Separation
DUAL_LAN=true



# ---------------------------------------- INCOMPLETE FEATURES

# Remove any USB devices from fstab & ensure UUID's for non-lvm partitions (default: true)
FSTAB=true

# Xen configuration settings in grub (default: dom0_mem=4096M dom0_max_vcpus=2)
XEN_CONF="dom0_mem=4096M dom0_max_vcpus=2"

# PCI BDF (Bus Device Function) from lspci for devices to hide using xen-pciback.hide (in array format):
#PCI_BDF=( "00:1d.0" "03:00.0" "03:00.1" "04:00.0" )
