#!/bin/sh
which xset &> /dev/null && (xset r rate 250 25 & xset b off & xset m 7 5) &
which nosleep-daemon &> /dev/null && (nosleep-daemon) &
which xrdb &> /dev/null && [ -f "$HOME/.Xresources" ] || [ -L "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"
which xdg-user-dirs-update &> /dev/null && (xdg-user-dirs-update) &
which compton &> /dev/null && (compton) &
which hsetroot &> /dev/null && (hsetroot -solid "#001E27") &
[ -f "$HOME/.fehbg" ] && [ -d "$HOME/.wallpaper/" ] && [ $(find $HOME/.wallpaper/ -type f | wc -l) -gt 0 ] && . "$HOME/.fehbg"
which tint2 &> /dev/null && (sleep 3 && tint2) &
which volumeicon &> /dev/null && (sleep 5 && volumeicon) &
which clipit &> /dev/null && (sleep 5 && clipit) &
which conky &> /dev/null && (sleep 10 && conky -d -q) &
