#!/bin/sh
[ -d ~/Pictures/Screenshots ] || mkdir -p ~/Pictures/Screenshots
xdpyinfo -ext XINERAMA | sed '/^  head #/!d;s///' |
while IFS=' :x@,' read i w h x y; do
    import -window root -crop ${w}x$h+$x+$y ~/Pictures/Screenshots/$(date +%F_%H%M%S_%N)-${i}.png
done

